; +----------------------------------------------------------------------------+
; | PEIX External interface box                                                |
; | Pozsar Zsolt <pozsarzs@gmail.com>, 2026. CC0 1.0 Universal                 |
; | peixapi.z80                                                                |
; | API of the PEIX equipment for CP/M-80, v0.1                                |
; +----------------------------------------------------------------------------+

PUBLIC PEIX

END
